### ISSUE TITLE
Not detecting correct bg autosart settings on LineageOS

### ISSUE THREAD

**Issue by caprilo** [wandomium/SmsLoc#14]
smsloc is not working at all. The log is full of 

Error: provider "network" does not exist

messages, and, when requesting background autostart permission, the message "Could not open settings" is shown. Im using version 1.1.4 in LineageOS 22.2.

**Comment by wandomium** [comment]
Basically - the app is probably working just fine but the log is definitely confusing and I will need to fix this!

**Comment by caprilo** [comment]
Yes, I do not include the quotation marks. The log says: "Aquire lock. Device idle: false"

**Comment by wandomium** [comment]
Did some debugging - found the problem. 

Three things you reported. One (nr 3) is a serious bug:
1. Network provider not found is not a problem but I will reduce the log output because it is misleading
2. Not opening bg autostart settings does not work on LineageOS because LineageOS does not have this. I applied a fix that will not open settings in this case 
3. !!! If the SMS was received without country code included, parsing did not work and response was not sent.  


Thank you for your patience and help with the logs. I will post here when a fix is available

**Comment by caprilo** [comment]
Thanks to you.

I installed the update from F-Droid, but the problem persists. I thought maybe requesting again the permissions would do, so I uninstalled and reinstalled, but it didn't work.

I also tested on an old Moto G7 Power with Android 10 and google services. After requesting the permissions, the app closes, and it continues to do so each time I re-open.

**Comment by caprilo** [comment]
Nope.

**Comment by caprilo** [comment]
Sure, here it is.

<img width="720" height="1560" alt="Image" src="https://github.com/user-attachments/assets/886c0016-b11b-4d98-ac50-99dfe896e691" />

**Comment by caprilo** [comment]
Sorry, it does work. I had not notice that I need to select a default SIM.

I might suggest that the app requests a default SIM the first time.

I also suggest to add a legend of what data is being received in the response (I can see 7 numbers, but don't know what they are, except for latitude and longitude).

Also I see that the map cannot be scrolled left or right, because the view changes to log or list. I also cannot see any locatiolocationn marked on it.

Thank  you very much for your work.

**Comment by wandomium** [comment]
If you move from Issues to code tab and scroll down you will see displayed app info with links to latest release.

Same place where the table explaining the interface (the numbers in sms) is
